# Generated by Django 3.2.5 on 2021-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
