# Generated by Django 3.2.5 on 2021-07-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descriptions',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
