# Generated by Django 3.2.5 on 2021-07-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210801_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
