# Generated by Django 3.2.5 on 2021-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210810_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
