# Generated by Django 3.2.5 on 2021-08-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_subscriber_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tips')),
                ('descriptions', models.TextField(max_length=660, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tips',
            },
        ),
    ]
