# Generated by Django 3.2.5 on 2021-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
